# Generated by Django 4.2.2 on 2023-07-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_email', models.EmailField(max_length=50)),
                ('teacher_qualification', models.CharField(max_length=100)),
                ('teacher_phone', models.CharField(max_length=20)),
                ('teacher_address', models.TextField()),
                ('joining_date', models.DateField()),
                ('aadhar_number', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=10)),
                ('teacher_image', models.ImageField(upload_to='images')),
                ('teacher_subjects', models.ManyToManyField(to='accounts.subject')),
            ],
        ),
    ]
