# Generated by Django 4.2.2 on 2023-07-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_leave_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='student_roll',
            new_name='roll',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='stud_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_qualification',
            new_name='qualification',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_subjects',
            new_name='subjects',
        ),
    ]
