# Generated by Django 4.2.2 on 2023-07-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_student_name_attendance_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='roll',
        ),
    ]
