# Generated by Django 4.2.2 on 2023-07-06 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_teacher_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='accounts.classroom'),
            preserve_default=False,
        ),
    ]
