# Generated by Django 4.2.2 on 2023-07-07 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_teacher_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.student'),
        ),
    ]
