# Generated by Django 4.2.2 on 2023-07-07 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_leave_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='accounts.student'),
        ),
    ]
